openapi: 3.0.1
info:
  title: Proper Properties API
  description: API para un inmobiliaria
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
tags:
  - name: clients
    description: Operaciones para fetch, add, update, y delete clientes
paths:
  /users/clients:
    get:
      tags:
        - clients
      operationId: getAllClients
      summary: Devuelve una lista de todos los clientes o todos los clientes según un parámetro especificado
      description: Devuelve una lista de todos los clientes y sus detalles según un parámetro especificado
      parameters:
        - name: surname
          in: query
          description: El/Los apellidos de cliente
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: El nombre de cliente
          required: false
          schema:
            type: string
        - name: dob
          in: query
          description: La fecha de nacimiento de cliente
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClientDTOOut"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      tags:
        - clients
      operationId: saveClient
      summary: Guarda un nuevo cliente
      description: Valida un objeto cliente y crea un nuevo cliente para guardar en el base de datos.
      requestBody:
        description: Un nuevo cliente
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientDTOIn"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientDTOOut"
        '400':
          description: Parse Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /users/clients/{clientId}:
    get:
      tags:
        - clients
      operationId: getUserById
      summary: Devuelve un cliente por client ID
      description: Devuelve un objeto de un cliente por client ID
      parameters:
        - name: clientId
          in: path variable
          description: La ID de cliente
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientDTOOut"
        '404':
          description: Client Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    put:
      tags:
       - clients
      operationId: updateClientById
      summary: Actualiza un cliente por client ID
      description: Actuliza un cliente por client ID y devuelve el resultado como un objeto ClientDTOOut
      parameters:
        - name: clientId
          in: path variable
          description: La ID de cliente
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: El objeto de cliente con detalles actualizadas
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientDTOIn"
      responses:
         '200':
           description: OK
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/ClientDTOOut"
         '404':
           description: Client Not Found
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/ErrorResponse"
         '500':
           description: Internal Server Error
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags:
        - clients
      summary: Elimina un cliente por el client ID
      description: Elimina un cliente por el client ID y devuelve un respuesta de No Content (void)
      parameters:
        - name: clientId
          in: path variable
          description: La ID de cliente
          required: true
          schema:
            type: integer
            format: int64
      responses:
         '204':
           description: La entidad fue eliminada con éxito
         '404':
           description: Client Not Found
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/ErrorResponse"
         '500':
           description: Internal Server Error
           content:
             application/json:
               schema:
                 $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ClientDTOIn:
      type: object
      properties:
        password:
          type: string
          example: "secret"
          description: La constraseña de cliente
      allOf:
        - $ref: "#/components/schemas/Client"
    ClientDTOOut:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: La ID de cliente
      allOf:
        - $ref: "#/components/schemas/Client"
    Client:
      type: object
      properties:
        name:
            type: string
            example: "Joe"
            description: El nombre de cliente
        surname:
            type: string
            example: "Bloggs"
            description: El/Los apellido(s) de cliente
        username:
            type: string
            example: "joe_bloggs"
            description: El nombre de usuario de cliente
        email:
            type: string?
            example: "joebloggs666@test.es"
            description: El email de cliente
        accountCreated:
            type: string
            example: "2023-07-21T14:12:09"
            description: La fecha cuando la cuenta de usuario fue creada
        dob:
            type: string
            example: "2023-07-21T14:12:09"
            description: La fecha de nacimiento de cliente
        isStudent:
            type: boolean
            example: false
            description: Indica si el ciente es estudiante o no
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          example: 404
          description: El código de estado de HTTP
        errorType:
          type: string
          example: Client Not Found Error
          description: Identifica el tipo de error
        message:
          type: string
          example: "Client not found with id: 55"
          description: Una descripción del error
















